# Generated by Django 4.2.29 on 2026-03-05 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('top', 'top'), ('bottom', 'bottom'), ('shoes', 'shoes')], max_length=20)),
                ('item', models.CharField(max_length=120)),
                ('style_semantics', models.JSONField(blank=True, default=list)),
                ('season_semantics', models.JSONField(blank=True, default=list)),
                ('usage_semantics', models.JSONField(blank=True, default=list)),
                ('color_semantics', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
